version: "3.4"

networks:
  d-optimas-net:
    driver: bridge

services:
  d-optimas-1:
    container_name: d-optimas-1
    image: felipedreis/d-optimas

    ports:
      - 2551:2551
    environment:
      DOPTIMAS_PORT: 2551
      DOPTIMAS_HOST: localhost
      DOPTIMAS_EXP_FILE: {{ experiment_path }}
      CASSANDRA_HOST: cassandra
      REPEAT: 20
    depends_on:
      - cassandra
      - cassandra-0
    restart: on-failure
    volumes:
      - type: bind
        source: {{ work_dir }}/results
        target: /data
        read_only: false
        bind:
          propagation: shared
    networks:
      - d-optimas-net
        #ipv4_address: 10.0.0.2

  cassandra:
    container_name: cassandra
    image: bitnami/cassandra:3.11.5
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_CLUSTER_NAME=d-optimas-db
      - CASSANDRA_PASSWORD_SEEDER=yes
    ports:
      - 9042:9042
      - 7000:7000
    restart: always
    volumes:
      - {{  work_dir }}/scripts/db.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - d-optimas-net

  cassandra-0:
    container_name: cassandra-0
    image: bitnami/cassandra:3.11.5
    environment:
      - CASSANDRA_HOST=cassandra-0
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=d-optimas-db
    depends_on:
      - cassandra
    restart: always
    networks:
      - d-optimas-net


volumes:
  results: