FROM amazoncorretto:11 AS run

WORKDIR /d-optimas/run

# Create native directory (will be empty)
RUN mkdir -p /d-optimas/native

COPY config/docker-config.conf ./
COPY experiments ./experiments/
COPY target/d-optimas-2.10-SNAPSHOT-deploy.jar ./d-optimas.jar
COPY scripts/run-d-optimas.sh ./
COPY config/log4j2.xml ./
COPY test_de.conf ./test_de.conf

RUN yum install lmdb -y

ENV CONFIG_FILE="docker-config.conf"
ENV REPEAT=1
ENV CASSANDRA_HOST=cassandra
ENV DOPTIMAS_EXP_FILE=test_de.conf
ENV COCO_LIB=/d-optimas/native/

# Overwrite entrypoint to use our test config if provided via env
ENTRYPOINT ./run-d-optimas.sh ${CONFIG_FILE} ${CASSANDRA_HOST} ${DOPTIMAS_EXP_FILE} ${REPEAT}
