- name: Deploy experiment server
  hosts: localhost
  gather_facts: no
  vars:
    experiment_path: 'experiments/tese/A/A.ILS.conf'
    experiment_name: 'function-problem-a'
    experiment_instance: 'A.ILS'
  roles:
    - gcloud-simulation-server

- name: Prepare instance
  hosts: new_instance
  connection: ssh
  become: True
  vars:
    experiment_path: 'experiments/tese/A/A.ILS.conf'
    experiment_name: 'function-problem-a'
    experiment_instance: 'A.ILS'
  roles:
    - d_optimas_prod