- name: Deploy experiment server
  hosts: localhost
  gather_facts: no
  vars:
    experiment_path: 'experiments/tese/A/A2.1.3.10.conf'
    experiment_name: 'function-problem-a'
    experiment_instance: 'A2.1.3.10'
    zone: "us-central1-a"
    region: "us-central1"
  roles:
    - gcloud-simulation-server

- name: Prepare instance
  hosts: new_instance
  connection: ssh
  become: True
  vars:
    experiment_path: 'experiments/tese/A/A2.1.3.10.conf'
    experiment_name: 'function-problem-a'
    experiment_instance: 'A2.1.3.10'
  roles:
    - d_optimas_prod